# monitoring-values.yaml
prometheus:
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: standard  # Using standard storage class for compatibility
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 20Gi
    retention: "15d"
    scrapeInterval: "15s"
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelector:
      matchLabels:
        monitoring: "true"
    externalUrl: https://compass-app.tum.de/prometheus/
    routePrefix: /

grafana:
  persistence:
    enabled: true
    storageClassName: standard
    accessModes: ["ReadWriteOnce"]
    size: 10Gi
  grafana.ini:
    server:
      domain: compass-app.tum.de
      root_url: https://compass-app.tum.de/grafana/
      serve_from_sub_path: true
    security:
      allow_embedding: true
  dashboards:
    default:
      team-git-happens-dashboard:
        json: |-
          {
            "annotations": { "list": [] },
            "panels": [
              {
                "type": "graph",
                "title": "HTTP Requests per Second",
                "targets": [
                  { "expr": "rate(http_requests_total[1m])", "legendFormat": "{{method}} {{handler}}" }
                ]
              },
              {
                "type": "graph",
                "title": "P95 Latency",
                "targets": [
                  { "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[5m])) by (le, handler))", "legendFormat": "{{handler}}" }
                ]
              },
              {
                "type": "graph",
                "title": "Error Rate (%)",
                "targets": [
                  {
                    "expr": "100 * rate(http_errors_total[5m]) / rate(http_requests_total[5m])",
                    "legendFormat": "error rate"
                  }
                ]
              },
              {
                "type": "graph",
                "title": "JVM Memory Usage",
                "targets": [
                  { "expr": "jvm_memory_used_bytes", "legendFormat": "{{area}}" }
                ]
              },
              {
                "type": "graph",
                "title": "Database Connections",
                "targets": [
                  { "expr": "hikaricp_connections_active", "legendFormat": "Active Connections" },
                  { "expr": "hikaricp_connections_idle", "legendFormat": "Idle Connections" }
                ]
              }
            ],
            "schemaVersion": 16,
            "title": "Team Git Happens - Services Overview",
            "version": 1
          }

serviceMonitors:
  enabled: true
