apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-webhook-config
  namespace: team-git-happens
data:
  alertmanager.yml: |
    global:
      # No SMTP configuration needed!

    route:
      group_by: ['alertname', 'cluster', 'service']
      group_wait: 10s
      group_interval: 10s
      repeat_interval: 1h
      receiver: 'webhook-notifications'

    receivers:
    - name: 'webhook-notifications'
      webhook_configs:
      - url: 'http://host.docker.internal:8080/webhook'  
        send_resolved: true
        title: 'TUM Course System Alert'
        text: |
          🚨 Alert: {{ .GroupLabels.alertname }}
          Status: {{ .Status }}
          {{ range .Alerts }}
          - {{ .Annotations.summary }}
          {{ end }}

    # Alternative: Discord webhook (if you have Discord)
    # - name: 'discord-notifications'
    #   webhook_configs:
    #   - url: 'https://discord.com/api/webhooks/YOUR_DISCORD_WEBHOOK_URL'
    #     send_resolved: true
