apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: git-happens-ingress
  namespace: team-git-happens
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "$http_origin"
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, PUT, POST, DELETE, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-headers: "Authorization, Content-Type"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
    - host: client-app.student.k8s.aet.cit.tum.de
      http:
        paths:
          # API routes routed to microservices
          - path: /api/auth(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: authentication-service
                port:
                  number: 8080
          - path: /api/courses(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: course-service
                port:
                  number: 8080
          - path: /api/review(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: review-service
                port:
                  number: 8080
          - path: /api/recommendation(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: recommendation-gateway
                port:
                  number: 8080
          # SPA catch-all routes
          - path: /(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: client-app
                port:
                  number: 80