apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: unified-app-ingress
  namespace: team-git-happens
  annotations:
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://k83-client-app.student.k8s.aet.cit.tum.de"
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, POST, PUT, DELETE, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-headers: "Authorization, Content-Type"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    cert-manager.io/cluster-issuer: letsencrypt-staging
spec:
  tls:
  - hosts:
    - k83-client-app.student.k8s.aet.cit.tum.de
    secretName: unified-app-tls
  rules:
  - host: k83-client-app.student.k8s.aet.cit.tum.de
    http:
      paths:
      # API Routes (müssen vor dem Frontend stehen!)
      - path: /auth/
        pathType: Prefix
        backend:
          service:
            name: authentication-service
            port:
              number: 8080
      - path: /courses/
        pathType: Prefix
        backend:
          service:
            name: course-service
            port:
              number: 8080
      - path: /reviews/
        pathType: Prefix
        backend:
          service:
            name: review-service
            port:
              number: 8080
      - path: /recommendations/
        pathType: Prefix
        backend:
          service:
            name: recommendation-gateway
            port:
              number: 8080
      # Frontend (muss als letztes stehen!)
      - path: /
        pathType: Prefix
        backend:
          service:
            name: client-app
            port:
              number: 80
