apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: unified-app-ingress
  namespace: team-git-happens
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, POST, PUT, DELETE, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-headers: "DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization"
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
spec:
  tls:
  - hosts:
    - k83-client-app.student.k8s.aet.cit.tum.de
    secretName: unified-app-tls
  rules:
  - host: k83-client-app.student.k8s.aet.cit.tum.de
    http:
      paths:
      # API Routes (must come before frontend!)
      - path: /api/auth(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: authentication-service
            port:
              number: 8080
      - path: /api/courses(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: course-service
            port:
              number: 8080
      - path: /api/categories(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: course-service
            port:
              number: 8080
      - path: /api/students(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: review-service
            port:
              number: 8080
      - path: /api/reviews(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: review-service
            port:
              number: 8080
      - path: /api/recommendations(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: recommendation-gateway
            port:
              number: 8080
      - path: /api/recommend(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: recommendation-gateway
            port:
              number: 8080
      - path: /api/genai(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: genai-service
            port:
              number: 8000
      # Frontend (must be last - handles all non-API routes with SPA fallback!)
      - path: /(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: client-app
            port:
              number: 80
