spring:
  datasource:
    # JDBC URL pointing at the local MySQL over TCP
    url:      jdbc:mysql://localhost:3306/devopsdb?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC # TODO: to be changed when using docker
    username: devops
    password: githappens!

  jpa:
    # schema evolution is managed via Flyway, not Hibernate
    hibernate:
      ddl-auto: none
    show-sql: true

  flyway:
    # Enable Flyway and tell it where to look for our scripts
    enabled: true
    locations: classpath:db/migration