INSERT IGNORE INTO category(name) VALUES
  ('Digital Biology and Digital Medicine'),
  ('Software Engineering'),
  ('Formal Methods'),
  ('Computer Arch., Networks & Dist. Systems');

INSERT IGNORE INTO course (id, title, description, credits)
VALUES
 -- Algorithms
  ('IN2239',   'Algorithmic Game Theory',
     'Analysis of strategic interactions and equilibria in computational settings.', 5),
  ('IN995401', 'Accepted Elective in Algorithms (Theory)',
     'In-depth study of algorithmic complexity and proof techniques.', 1),
  ('IN995402', 'Accepted Elective in Algorithms (Theory)',
     'Advanced exploration of theoretical foundations and algorithm analysis.', 1),
  ('IN2211',   'Auction Theory and Market Design',
     'Mechanism design, bidding strategies, and market efficiency.', 5),
  ('IN2007',   'Complexity Theory',
     'Classification of computational problems by hardness and resource bounds.', 8),
  ('IN2229',   'Computational Social Choice',
     'Algorithmic approaches to collective decision making and voting rules.', 6),
  ('IN2003',   'Efficient Algorithms and Data Structures',
     'Fundamental data structures and their use in high-performance algorithms.', 8),
  ('IN2004',   'Efficient Algorithms and Data Structures II',
     'Advanced data structure design and optimization techniques.', 8),
  ('IN2360',   'Advanced Algorithms',
     'Design and analysis of cutting-edge algorithmic solutions.', 6),
  ('IN2304',   'Online and Approximation Algorithms',
     'Algorithms under uncertainty and performance guarantees via approximation.', 8),
  ('IN0024',   'Operations Research',
     'Mathematical optimization methods for decision making and logistics.', 6),
  ('IN99540',  'Accepted Elective Module in Algorithms',
     'Specialized elective covering modern algorithmic methods.', 1),
  ('IN99541',  'Accepted Elective Module in Algorithms',
     'Hands-on module on advanced algorithmic applications.', 1),
  ('IN99542',  'Accepted Elective Module in Algorithms',
     'Selected topics in cutting-edge algorithm research.', 1),

  -- Computer Graphics & Vision
  ('IN995026', 'Accepted Elective in Computer Graphics and Vision (Theory)',
     'Theoretical principles underlying rendering and vision algorithms.', 1),
  ('IN2246',   'Computer Vision I: Variational Methods',
     'Introduction to variational techniques in image processing and reconstruction.', 8),
  ('IN2228',   'Computer Vision II: Multiple View Geometry',
     'Geometry and algorithms for reconstructing 3D scenes from multiple images.', 8),
  ('IN2124',   'Basic Mathematical Methods for Imaging and Visualization',
     'Mathematical foundations for image analysis and visualization techniques.', 5),
  ('IN0037',   'Game Physics',
     'Physics simulation techniques for interactive virtual environments.', 6),
  ('IN2297',   'Geometry Processing',
     'Algorithms for processing and analyzing geometric shapes and meshes.', 6),
  ('IN2133',   'Principles of Computer Vision',
     'Core concepts and methods in computer vision and pattern recognition.', 4),
  ('IN2015',   'Image Synthesis',
     'Techniques for generating realistic images using computational models.', 5),
  ('IN2369',   'Machine Vision',
     'Application of computer vision methods in industrial automation and inspection.', 6),
  ('IN2409',   'Inverse Problems in Medical Imaging',
     'Reconstruction methods for medical imaging modalities and inverse problems.', 5),
  ('IN2392',   'Machine Learning for 3D Geometry',
     'Applying machine learning algorithms to 3D shape analysis and reconstruction.', 6),
  ('IN2236',   'Virtual Physics: Using Modern Modeling Methodologies for Computer Simulation',
     'Modern modeling techniques for simulating physical systems in graphics.', 4),
  ('IN2026',   'Visual Data Analytics',
     'Data-driven visualization and analytics for large-scale visual datasets.', 5),
  ('MH4L004277', 'XR: Virtual-, Mixed-, and Augmented Reality',
     'Fundamentals and applications of XR technologies in interactive systems.', 5),
  ('IN2354',   '3D Scanning & Motion Capture',
     'Techniques for capturing and processing 3D geometry and motion data.', 6),
  ('IN2111',   '3D User Interfaces',
     'Design and implementation of 3D interfaces for immersive user experiences.', 6),

  -- Databases & Information Systems
  ('IN3100',     'Selected Topics in Databases and Information Systems',
     'Explores current research themes and innovations in database systems.', 5),
  ('IN2386',     'Cloud-Based Data Processing',
     'Techniques for processing large datasets using cloud computing platforms.', 5),
  ('CIT3230001', 'Code Generation for Data Processing',
     'Compiler and runtime strategies for generating high-performance data pipelines.', 6),
  ('CIT3230004', 'Data Processing on Modern Hardware',
     'Optimizing data workloads for GPUs, FPGAs, and other accelerators.', 5),
  ('CIT3230003', 'Data Structure Engineering',
     'Designing and implementing efficient data structures for real-world applications.', 5),
  ('IN2118',     'Database Systems on Modern CPU Architectures',
     'Leveraging multi-core and vectorized CPUs for high-speed database operations.', 6),
  ('IN2288',     'Event Processing',
     'Architectures and techniques for real-time stream and event-driven systems.', 5),
  ('IN2267',     'Transaction Systems',
     'Principles and protocols for reliable, concurrent transaction processing.', 6),

  -- Machine Learning & Analytics
  ('IN2410',      'Causality',
     'Study of cause–effect relationships and methods for causal inference.', 8),
  ('CIT4230004',  'Statistical Foundations of Learning',
     'Fundamental statistical techniques underpinning modern machine learning.', 8),
  ('IN99555',     'Accepted Elective in Machine Learning and Analytics',
     'Elective covering core principles and applications of ML and analytics.', 1),
  ('IN99556',     'Accepted Elective in Machine Learning and Analytics',
     'Elective covering core principles and applications of ML and analytics.', 1),
  ('IN99557',     'Accepted Elective in Machine Learning and Data Analytics',
     'Elective exploring machine learning methods for data-driven insights.', 1),
  ('IN99558',     'Accepted Elective in Machine Learning and Analytics',
     'Elective covering core principles and applications of ML and analytics.', 1),
  ('IN99559',     'Accepted Elective in Machine Learning and Analytics',
     'Elective covering core principles and applications of ML and analytics.', 1),
  ('CIT433027',   'Advanced Deep Learning for Robotics',
     'Applying deep learning techniques to robotic perception and control.', 8),
  ('CIT4230003',  'Advanced Machine Learning: Deep Generative Models',
     'In-depth study of generative model architectures and their applications.', 3),
  ('IN2408',      'Artificial Intelligence in Medicine II',
     'Advanced AI methods for diagnostics and treatment in healthcare.', 5),
  ('IN3440',      'Selected Topics in Machine Learning and Analytics',
     'Explores current research topics and innovations in ML and analytics.', 5),
  ('CIT4230006',  'Causal Inference in Time Series',
     'Methods for uncovering causal relationships in temporal data.', 5),
  ('IN2028',      'Business Analytics and Machine Learning',
     'Integrating ML techniques with business decision-making processes.', 5),
  ('IN2339',      'Data Analysis and Visualization in R',
     'Data manipulation and visualization using the R programming language.', 6),
  ('IN2030',      'Data Mining and Knowledge Discovery',
     'Techniques for extracting patterns and insights from large datasets.', 3),
  ('CIT433021',   'Fundamentals of Foundation Models',
     'Core principles, architectures, and use cases of foundation models.', 5),
  ('IN2346',      'Introduction to Deep Learning',
     'Basics of neural networks and deep learning architectures.', 6),
  ('IN2395',      'Legal Data Science and Informatics',
     'Application of data science methods to legal documents and case analysis.', 6),
  ('IN2064',      'Machine Learning',
     'Fundamental algorithms and techniques for supervised and unsupervised learning.', 8),
  ('IN2357',      'Machine Learning for Computer Vision',
     'Applying ML algorithms to image recognition and visual data processing.', 5),
  ('IN2323',      'Machine Learning for Graphs and Sequential Data',
     'Graph-based and sequential ML methods for structured and time-series data.', 5),
  ('CIT423003',   'Multimodal Deep Learning',
     'Deep learning techniques for fusing and analyzing multimodal data.', 5),
  ('IN2361',      'Natural Language Processing',
     'Algorithms and models for processing and understanding human language.', 6),

  -- Robotics
  ('CIT433034', 'Advanced Multi-Fingered Robotic Hands: Dextrous Manipulation and Learning AI',
     'Design and control of dextrous robotic hands using machine learning techniques.', 3),
  ('IN3460',    'Selected Topics in Robotics',
     'Explores cutting-edge research and applications in robotics.', 5),
  ('CIT436000', 'Legged Robots',
     'Kinematics, dynamics, and control methods for legged robotic platforms.', 5),
  ('IN2222',    'Cognitive Systems',
     'Integration of perception, reasoning, and learning in intelligent agents.', 5),
  ('IN2305',    'Cyber-Physical Systems',
     'Architectures and algorithms for safe, real-time integration of computation and the physical world.', 6),
  ('IN2060',    'Real-Time Systems',
     'Principles and implementation of systems with strict timing constraints.', 6),
  ('IN2061',    'Introduction to Digital Signal Processing',
     'Fundamentals of DSP algorithms for analysis and processing of signals.', 7),
  ('IN2383',    'Formal Methods for Cyber-Physical Systems',
     'Mathematical specification and verification techniques for CPS safety and correctness.', 5),
  ('IN2406',    'Fundamentals of Artificial Intelligence',
     'Core AI algorithms including search, planning, and knowledge representation.', 6),
  ('CIT433039', 'Intelligent Robots with a Sense of Smell',
     'Development of olfactory sensors and AI models for robotic odor detection.', 7),
  ('CIT3330000','Introduction to Mobile Robotics',
     'Basic principles of navigation, perception, and control in mobile robots.', 6),
  ('MW2411',    'Concepts and Software Design for Cyber-Physical Systems',
     'Software engineering techniques for developing robust CPS applications.', 5),
  ('IN2405',    'Neuroprosthetics: Artificial Limbs',
     'Design and control of neural-interface driven prosthetic devices.', 5),
  ('IN2308',    'Programming and Control for Human-Robot Interaction',
     'Software frameworks and control strategies for safe HRI systems.', 5),
  ('IN2138',    'Robot Motion Planning',
     'Algorithms for path planning and navigation in dynamic environments.', 5),
  ('IN2067',    'Robotics',
     'Comprehensive introduction to robot design, control, and applications.', 6),
  ('IN2068',    'Sensor-based Robotic Manipulation and Locomotion',
     'Use of sensor feedback for adaptive robot movement and manipulation.', 3),
  ('CIT4330017','Trustworthy Machine Learning Systems',
     'Techniques for ensuring reliability, safety, and fairness in ML-driven systems.', 3),  

  --  Digital Biology and Digital Medicine 
  ('IN3420',       'Selected Topics in Digital Biology and Digital Medicine',
     'Explores computational methods applied to biology and digital medicine research.', 5),
  ('CIT4230001',   'Computational Modeling for System Genetics',
     'Mathematical and computational techniques for modeling genetic regulatory networks.', 6),
  ('IN2021',       'Computer Aided Medical Procedures',
     'Development and evaluation of software tools for guiding medical interventions.', 6),
  ('IN2022',       'Computer Aided Medical Procedures II',
     'Advanced techniques for computer-assisted surgical planning and navigation.', 5),
  ('IN2292',       'Introduction to Surgical Robotics',
     'Principles of robotic systems for enhancing surgical precision and outcomes.', 6),
  ('IN2393',       'Machine Learning for Regulatory Genomics',
     'Applying machine learning algorithms to genomic data for regulatory element prediction.', 6),
  ('IN2293',       'Medical Augmented Reality',
     'Use of AR technologies for visualization and guidance in medical applications.', 5),
  ('IN2322',       'Protein Prediction I for Computer Scientists',
     'Computational approaches for protein structure and function prediction.', 8),
  ('IN2291',       'Protein Prediction II for Computer Scientists',
     'Advanced methods in protein folding and structural bioinformatics.', 8),

  -- Software Engineering
  ('IN2309',     'Advanced Topics of Software Engineering',
     'Explores state-of-the-art methods and tools in software engineering research.', 8),
  ('CIT423002',  'AI Testing',
     'Methods and frameworks for testing robustness and correctness of AI systems.', 5),
  ('IN3430',     'Selected Topics in Software Engineering',
     'Covers emerging topics in the development of complex software-intensive applications.', 5),
  ('IN2359',     'Blockchain-based Systems Engineering',
     'Design and implementation of blockchain and distributed ledger technologies.', 5),
  ('CIT423001',  'DevOps: Engineering for Deployment and Operations',
     'Practices and tools for continuous integration, delivery, and system operations.', 6),
  ('CIT4230005', 'Engineering Resilient Cognitive Systems',
     'Techniques for building robust and reliable cognitive AI applications.', 3),
  ('IN2084',     'Advanced Topics of Software Testing',
     'In-depth exploration of advanced testing techniques and quality assurance.', 5),
  ('IN2105',     'Business Process Technologies and Management',
     'Modeling, automation, and optimization of business processes with IT solutions.', 5),
  ('IN2079',     'IT-Consulting',
     'Principles and best practices for providing IT consultancy services.', 3),
  ('IN2081',     'Patterns in Software Engineering',
     'Software design patterns and their application in complex systems.', 5),
  ('IN2394',     'Requirements Engineering',
     'Elicitation, specification, and management of software requirements.', 3),
  ('IN2087',     'Software Engineering for Business Applications - Master''s Course: Web Application Engineering',
     'Frameworks and architectures for developing enterprise web applications.', 8),
  ('IN2235',     'Software Engineering in an Industrial Setting',
     'Practices and challenges of large-scale software development in industry.', 3),
  ('CIT4230000', 'Strategic IT Management',
     'Strategic planning, governance, and management of IT resources.', 4),

  -- Formal Methods
  ('IN2041', 'Automata and Formal Languages',
     'Fundamental models of computation and the grammars that define languages.', 8),
  ('IN2227', 'Compiler Construction I',
     'Principles and implementation techniques for building compilers.', 5),
  ('IN2347', 'Functional Data Structures',
     'Design and analysis of persistent and purely functional data structures.', 5),
  ('IN2358', 'Lambda Calculus',
     'Formal study of computation based on function abstraction and application.', 5),
  ('IN2049', 'Logic',
     'Mathematical logic foundations including propositional and predicate calculi.', 8),
  ('IN2050', 'Model Checking',
     'Automated verification of system models against temporal logic specifications.', 8),
  ('IN2052', 'Petri Nets',
     'Modeling and analysis of concurrent systems using Petri net formalism.', 5),
  ('IN2053', 'Program Optimization',
     'Techniques for improving program performance through code analysis and transformation.', 8),
  ('IN2055', 'Semantics',
     'Formal semantics of programming languages, including operational and denotational approaches.', 8),
  ('IN2040', 'Virtual Machines',
     'Design and implementation of software-based execution environments.', 6),
  ('CIT3230000', 'Advanced Concepts of Programming Languages',
     'In-depth exploration of modern language design, type systems, and implementation techniques.', 6),
     
  --Computer Architecture, Computer Networks and Distributed Systems (RRV)
  ('IN2315',      'Network Coding',
     'Techniques for transmitting data efficiently and reliably using coding theory in networks.', 6),
  ('IN2076',      'Advanced Computer Architecture',
     'Study of modern CPU design including pipelining, caching, and parallel execution.', 6),
  ('IN2097',      'Advanced Computer Networking',
     'In-depth exploration of high-speed networking protocols and architectures.', 5),
  ('IN3450',      'Selected Topics in Computer Architecture, Computer Networks and Distributed Systems',
     'Current research and innovations at the intersection of architecture, networking, and distributed computing.', 5),
  ('IN2073',      'Cloud Computing',
     'Principles and platforms for on-demand resource provisioning and scalable services in the cloud.', 4),
  ('IN2324',      'Connected Mobility Basics',
     'Fundamentals of vehicle-to-everything communication and intelligent transportation systems.', 8),
  ('CIT4330013',  'Design Automation and Simulation for Microfluidic Devices',
     'Design methodologies and simulation tools for lab-on-a-chip microfluidic systems.', 5),
  ('IN2259',      'Distributed Systems',
     'Principles and algorithms for building scalable and fault-tolerant distributed applications.', 5),
  ('EI70630',     'HW/SW Codesign',
     'Methodologies for the joint design of hardware and software components in embedded systems.', 5),
  ('CIT433032',   'Logic Synthesis and Physical Design',
     'Automation techniques for synthesizing and laying out digital logic circuits.', 6),
  ('CIT433031',   'Machine Learning for Electronic Design Automation and Manufacturing',
     'Applications of ML to optimize EDA processes and manufacturing workflows.', 5),
  ('IN2333',      'Protocol Design',
     'Design and evaluation of communication protocols for reliable and efficient data exchange.', 8),
  ('IN2125',      'Virtualization Techniques',
     'Techniques for implementing and managing virtual machines and hypervisors.', 5);


-- 3) Link each course to its module category
INSERT IGNORE INTO course_category (course_id, category_name)
VALUES
  -- Algorithms
  ('IN2239',   'Algorithms'),
  ('IN995401', 'Algorithms'),
  ('IN995402', 'Algorithms'),
  ('IN2211',   'Algorithms'),
  ('IN2007',   'Algorithms'),
  ('IN2229',   'Algorithms'),
  ('IN2003',   'Algorithms'),
  ('IN2004',   'Algorithms'),
  ('IN2360',   'Algorithms'),
  ('IN2304',   'Algorithms'),
  ('IN0024',   'Algorithms'),
  ('IN99540',  'Algorithms'),
  ('IN99541',  'Algorithms'),
  ('IN99542',  'Algorithms'),
  -- Computer Graphics & Vision
  ('IN995026', 'Computer Graphics & Vision'),
  ('IN2246',   'Computer Graphics & Vision'),
  ('IN2228',   'Computer Graphics & Vision'),
  ('IN2124',   'Computer Graphics & Vision'),
  ('IN0037',   'Computer Graphics & Vision'),
  ('IN2297',   'Computer Graphics & Vision'),
  ('IN2133',   'Computer Graphics & Vision'),
  ('IN2015',   'Computer Graphics & Vision'),
  ('IN2369',   'Computer Graphics & Vision'),
  ('IN2409',   'Computer Graphics & Vision'),
  ('IN2392',   'Computer Graphics & Vision'),
  ('IN2236',   'Computer Graphics & Vision'),
  ('IN2026',   'Computer Graphics & Vision'),
  ('MH4L004277','Computer Graphics & Vision'),
  ('IN2354',   'Computer Graphics & Vision'),
  ('IN2111',   'Computer Graphics & Vision'),
    -- Databases & Information Systems
  ('IN3100',     'Databases and Information Systems'),
  ('IN2386',     'Databases and Information Systems'),
  ('CIT3230001', 'Databases and Information Systems'),
  ('CIT3230004', 'Databases and Information Systems'),
  ('CIT3230003', 'Databases and Information Systems'),
  ('IN2118',     'Databases and Information Systems'),
  ('IN2288',     'Databases and Information Systems'),
  ('IN2267',     'Databases and Information Systems'),
  -- Machine Learning & Analytics
  ('IN2410',      'Machine Learning and Analytics'),
  ('CIT4230004',  'Machine Learning and Analytics'),
  ('IN99555',     'Machine Learning and Analytics'),
  ('IN99556',     'Machine Learning and Analytics'),
  ('IN99557',     'Machine Learning and Analytics'),
  ('IN99558',     'Machine Learning and Analytics'),
  ('IN99559',     'Machine Learning and Analytics'),
  ('CIT433027',   'Machine Learning and Analytics'),
  ('CIT4230003',  'Machine Learning and Analytics'),
  ('IN2408',      'Machine Learning and Analytics'),
  ('IN3440',      'Machine Learning and Analytics'),
  ('CIT4230006',  'Machine Learning and Analytics'),
  ('IN2028',      'Machine Learning and Analytics'),
  ('IN2339',      'Machine Learning and Analytics'),
  ('IN2030',      'Machine Learning and Analytics'),
  ('CIT4230017',   'Machine Learning and Analytics'),
  ('IN2346',      'Machine Learning and Analytics'),
  ('IN2395',      'Machine Learning and Analytics'),
  ('IN2064',      'Machine Learning and Analytics'),
  ('IN2357',      'Machine Learning and Analytics'),
  ('IN2323',      'Machine Learning and Analytics'),
  ('CIT423003',   'Machine Learning and Analytics'),
  ('IN2361',      'Machine Learning and Analytics'),
  ('IN2064',      'Machine Learning and Analytics'),
  ('IN2357',      'Machine Learning and Analytics'),
  ('IN2323',      'Machine Learning and Analytics'),
  ('CIT423003',   'Machine Learning and Analytics'),
  ('IN2361',      'Machine Learning and Analytics'),
  -- Robotics
  ('CIT433034', 'Robotics'),
  ('IN3460',    'Robotics'),
  ('CIT436000', 'Robotics'),
  ('IN2222',    'Robotics'),
  ('IN2305',    'Robotics'),
  ('IN2060',    'Robotics'),
  ('IN2061',    'Robotics'),
  ('IN2383',    'Robotics'),
  ('IN2406',    'Robotics'),
  ('CIT433039', 'Robotics'),
  ('CIT3330000','Robotics'),
  ('MW2411',    'Robotics'),
  ('IN2405',    'Robotics'),
  ('IN2308',    'Robotics'),
  ('IN2138',    'Robotics'),
  ('IN2067',    'Robotics'),
  ('IN2068',    'Robotics'),
  ('CIT4330017','Robotics'),
  -- Digital Biology and Digital Medicine
  ('IN3420',       'Digital Biology and Digital Medicine'),
  ('CIT4230001',   'Digital Biology and Digital Medicine'),
  ('IN2021',       'Digital Biology and Digital Medicine'),
  ('IN2022',       'Digital Biology and Digital Medicine'),
  ('IN2292',       'Digital Biology and Digital Medicine'),
  ('IN2393',       'Digital Biology and Digital Medicine'),
  ('IN2293',       'Digital Biology and Digital Medicine'),
  ('IN2322',       'Digital Biology and Digital Medicine'),
  ('IN2291',       'Digital Biology and Digital Medicine'),
  -- Software Engineering
  ('IN2309',     'Software Engineering'),
  ('CIT423002',  'Software Engineering'),
  ('IN3430',     'Software Engineering'),
  ('IN2359',     'Software Engineering'),
  ('CIT423001',  'Software Engineering'),
  ('CIT4230005', 'Software Engineering'),
  ('IN2084',     'Software Engineering'),
  ('IN2105',     'Software Engineering'),
  ('IN2079',     'Software Engineering'),
  ('IN2081',     'Software Engineering'),
  ('IN2394',     'Software Engineering'),
  ('IN2087',     'Software Engineering'),
  ('IN2235',     'Software Engineering'),
  ('CIT4230000', 'Software Engineering'),
  -- Formal Methods
  ('IN2041', 'Formal Methods'),
  ('IN2227', 'Formal Methods'),
  ('IN2347', 'Formal Methods'),
  ('IN2358', 'Formal Methods'),          
  ('IN2049', 'Formal Methods'),
  ('IN2050', 'Formal Methods'),
  ('IN2052', 'Formal Methods'),
  ('IN2053', 'Formal Methods'),
  ('IN2055', 'Formal Methods'),
  ('IN2040', 'Formal Methods'),
  ('CIT3230000', 'Formal Methods'),      
  -- Computer Architecture, Computer Networks and Distributed Systems (RRV)
  ('IN2315',      'Computer Arch., Networks & Dist. Systems'),
  ('IN2076',      'Computer Arch., Networks & Dist. Systems'),
  ('IN2097',      'Computer Arch., Networks & Dist. Systems'),
  ('IN3450',      'Computer Arch., Networks & Dist. Systems'),
  ('IN2073',      'Computer Arch., Networks & Dist. Systems'),
  ('IN2324',      'Computer Arch., Networks & Dist. Systems'),
  ('CIT4330013',  'Computer Arch., Networks & Dist. Systems'),
  ('IN2259',      'Computer Arch., Networks & Dist. Systems'),
  ('EI70630',     'Computer Arch., Networks & Dist. Systems'),
  ('CIT433032',   'Computer Arch., Networks & Dist. Systems'),
  ('CIT433031',   'Computer Arch., Networks & Dist. Systems'),
  ('IN2333',      'Computer Arch., Networks & Dist. Systems'),
  ('IN2125',      'Computer Arch., Networks & Dist. Systems');